name: listfiles

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  list-png-files:
    runs-on: ubuntu-latest
    outputs:
      file: ${{ steps.set-files.outputs.file }}
    steps:
      - uses: actions/checkout@v2
      - id: set-files
        run: echo "file=$(ls *.* | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT
  check:
    needs: list-png-files
    runs-on: ubuntu-latest
    strategy:
        matrix:
            file: ${{ fromJson(needs.list-png-files.outputs.file) }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - run: |
          echo "${{ matrix.file }}"
